name: NPCDestinations_Farmer
main: net.livecar.nuttyworks.destinations_farmer.BukkitPlugin
description: Plugin for NPC Destinations that enables NPC farmers.
version: 2.3.3
author: Sir_Nutty@Spigot
api-version: 1.13
softdepend: [NPC_Destinations]
website: https://www.spigotmc.org/resources/nunpcdestinations-create-living-npcs-1-8-3-1-10-2.13863/
